name: Build and Release Python Executables

on:
  push:
    branches:
      - master
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install PyInstaller
        run: pip install pyinstaller

      - name: Build Executables
        run: |
          pyinstaller --noconfirm --onefile --console --icon "ico.ico" --name "gdansk_v1.0.1" --add-data "utils:utils/" "gdansk.py"
          pyinstaller --noconfirm --onefile --console --icon "ico.ico" --name "slupsk_v1.0.1" --add-data "utils:utils/" "slupsk.py"

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v1.0.1
          release_name: "Release v1.0.1"
          body: "Executable files for Gdańsk and Słupsk are collected and uploaded."
          draft: false
          prerelease: false

      - name: Upload Gdańsk Executable to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/gdansk_v1.0.1
          asset_name: gdansk_v1.0.1.exe
          asset_content_type: application/octet-stream

      - name: Upload Słupsk Executable to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/slupsk_v1.0.1
          asset_name: slupsk_v1.0.1.exe
          asset_content_type: application/octet-stream
