name: Build and Publish Release

on:
  push:
    branches:
      - master
  release:
    types:
      - created

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install PyInstaller
        run: pip install pyinstaller

      - name: Build Executables
        run: |
          pyinstaller --noconfirm --onefile --console --icon "ico.ico" --name "gdansk_v1.0.1.exe" --add-data "utils;utils/" "gdansk.py"
          pyinstaller --noconfirm --onefile --console --icon "ico.ico" --name "slupsk_v1.0.1.exe" --add-data "utils;utils/" "slupsk.py"

      - name: Show built files (debug)
        run: dir dist

      - name: Upload executables as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: executables
          path: dist/*.exe

  release:
    needs: build
    runs-on: windows-latest

    steps:
      - name: Download built executables
        uses: actions/download-artifact@v4
        with:
          name: executables
          path: dist

      - name: Show downloaded files (debug)
        run: dir dist

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*.exe
          tag_name: ${{ github.ref_name }}
          name: "Release ${{ github.ref_name }}"
          body: "Executable files for Gdańsk and Słupsk (version 1.0.1) are included in this release."
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}